# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"

#  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
     vb.name = "Project_6"
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get -y install wget python3 python3-venv python3-pip libpq-dev python3-dev
    sudo python3 -m pip install psycopg2 django
  SHELL

  config.vm.provision "file", source: "./main.py", destination: "$HOME/pythonproject/"

end
